baseURL = "https://g-lihuan.github.io/glihuan.github.io/"
languageCode = "zh-cn"
title = "My New Hugo Site"
theme = "anatole"
publishdir = "./docs"

[params]
title = "I'm Lihuan"
author = "lihuan"
profilePicture = "images/profile.jpeg"